[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = [
    "ClancyERC721", "ClancyERC20", "ClancyERC721Airdroppable",
    "OffersERC721", "EscrowERC721", 
    "Reels", "Series1Case", 
    ]


[rpc_endpoints]
# Test Nets
sentinel_dev = '{RPC_URL_SENTINEL_DEV}'
mumbai = '{RPC_URL_MUMBAI}'
sepolia = '{RPC_URL_SEPOLIA}'

# Main Nets
mainnet = '{RPC_URL_MAINNET}'
polygon = '{RPC_URL_POLYGON}'

[etherscan]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# forge test --match-path test/mev/FlashDance.t.sol --rpc-url mainnet -vvvv